[package]
name = "animation_blending"
version = "0.1.0"
edition = "2024"
description = "Library and GUI tool designed for blending animations."

[dependencies]
bevy = {version =  "0.17.3", features = ["hotpatching"]}
