[package]
name = "tps_camera"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = "0.4.1"
bevy = "0.17.2"
rand = "0.9.1"

[dependencies.bevy_dolly]
git = "https://github.com/Gaeric/bevy_dolly/"
branch = "main"
